// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApjmCzw1qlOhREkSgyrDsyaZ-5hpHAeos',
    appId: '1:893158816408:web:d5b1ed2ebb29683de9eeed',
    messagingSenderId: '893158816408',
    projectId: 'road-rescue-app-sdd',
    authDomain: 'road-rescue-app-sdd.firebaseapp.com',
    storageBucket: 'road-rescue-app-sdd.appspot.com',
    measurementId: 'G-23JSMH30VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz0QoEFEwSFXBqvu9C3GduudOAZDY7MvI',
    appId: '1:893158816408:android:a8906c27b6e5e86ee9eeed',
    messagingSenderId: '893158816408',
    projectId: 'road-rescue-app-sdd',
    storageBucket: 'road-rescue-app-sdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGfZPy16vJAJyzw6Tw_HOMHF_s8ijYXJE',
    appId: '1:893158816408:ios:518792e96fc92c36e9eeed',
    messagingSenderId: '893158816408',
    projectId: 'road-rescue-app-sdd',
    storageBucket: 'road-rescue-app-sdd.appspot.com',
    iosBundleId: 'com.example.roadRescueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGfZPy16vJAJyzw6Tw_HOMHF_s8ijYXJE',
    appId: '1:893158816408:ios:23b915225ae435a5e9eeed',
    messagingSenderId: '893158816408',
    projectId: 'road-rescue-app-sdd',
    storageBucket: 'road-rescue-app-sdd.appspot.com',
    iosBundleId: 'com.example.roadRescueApp.RunnerTests',
  );
}
